DROP TABLE IF EXISTS `go_links_20`;
DROP TABLE IF EXISTS `cf_20`;
DROP TABLE IF EXISTS `ti_tickets`;
DROP TABLE IF EXISTS `ti_messages`;
DROP TABLE IF EXISTS `ti_types`;
DROP TABLE IF EXISTS `ti_statuses`;
DROP TABLE IF EXISTS `ti_templates`;
DROP TABLE IF EXISTS `ti_settings`;
DROP TABLE IF EXISTS `ti_rates`;
DROP TABLE IF EXISTS `ti_tickets_custom_fields`;
DROP TABLE IF EXISTS `ti_groups`, `ti_type_groups`;